version: '3.3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080
    restart: on-failure
    environment:
      POSTGRES_DB: 'sbb'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_HOST: 'db'
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - /pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always

volumes:
  pgdata:
